---

- name: get current nginx config
  ansible.builtin.shell: "nginx -qTV || echo '' | grep -Ev '^[[:space:]]*(#.*)?$'"
  register: curconf
  changed_when: false
  check_mode: false
  failed_when: false

- name: nginx facts
  ansible.builtin.set_fact:
    has_http2: '{% if curconf.stderr is search("--with-http_v2_module") %}{{ true }}{% else %}{{ false }}{% endif %}'
    has_http3: '{% if curconf.stderr is search("--with-http_v3_module") %}{{ true }}{% else %}{{ false }}{% endif %}'

- name: site vars
  ansible.builtin.include_vars: site.yml

- name: site fact
  ansible.builtin.set_fact:
    site: '{{ default_site | combine(onesite) }}'
    http3_reuseport: '{% if curconf.stdout is search("listen + [\[\]0-9a-fA-F\.:]*"+siteport+" *quic +reuseport") %}{% else %} reuseport{% endif %}'

- name: site includes
  ansible.builtin.template:
    dest: '{{ nginx_etcdir }}/{{ item | regex_replace("^.* ","") | basename | regex_replace("\.j2$","") }}'
    src: '{{ lookup("first_found", include_locations | product(["/"+item | regex_replace(" .*$","") ]) | map("join") | list) }}'
  with_items: '{{ site.nginx_includes }}'
  when: '"nginx_includes" in site'
  notify: reload nginx

- name: site precludes
  ansible.builtin.template:
    dest: '{{ nginx_etcdir }}/{{ item | regex_replace("^.* ","") | basename | regex_replace("\.j2$","") }}'
    src: '{{ lookup("first_found", include_locations | product(["/"+item | regex_replace(" .*$","") ]) | map("join") | list) }}'
  with_items: '{{ site.nginx_precludes }}'
  when: '"nginx_precludes" in site'
  notify: reload nginx

- name: conf includes
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ nginx_etcdir }}/conf.d/{{ item | regex_replace(".*/([^/]+)$","\1") }}'
    mode: '0644'
  with_fileglob:
    - '{{ site.id }}/nginx/conf.d/*.conf'
  notify: reload nginx

- name: conf includes (templates)
  ansible.builtin.template:
    src: '{{ item }}'
    dest: '{{ nginx_etcdir }}/conf.d/{{ item | regex_replace(".*/([^/]+)\.j2$","\1") }}'
    mode: '0644'
  with_fileglob:
    - '{{ site.id }}/nginx/conf.d/*.conf.j2'
  notify: reload nginx

- name: root dir
  ansible.builtin.copy:
    dest: '{{ site.rootdir }}/'
    src: '{{ site.rootsrc }}/'
    mode: a=rX,u+w
    owner: root
  when: '"rootsrc" in site and site.rootsrc is defined and site.rootsrc != ""'

- name: stat rootdir
  ansible.builtin.stat:
    path: '{{ site.rootdir }}'
  register: statrootdir

- name: mkdir root dir
  ansible.builtin.file:
    dest: '{{ site.rootdir }}'
    state: directory
    mode: '0755'
    owner: root
  when: not statrootdir.stat.exists and nginx_create_rootdir

- name: x509 certs
  block:
    - name: mkdir
      ansible.builtin.file:
        path: '{{ tls_certs_dir }}/private'
        state: directory
        mode: '0711'
    - name: x509 cert
      ansible.builtin.copy:
        src: '{{ site.tls_cert }}'
        dest: '{{ tls_certs_dir }}/{{ site.cert_name }}.crt'
        mode: '0400'
        force: no
      notify: reload nginx
    - name: x509 key
      ansible.builtin.copy:
        src: '{{ site.tls_key }}'
        dest: '{{ tls_certs_dir }}/private/{{ site.cert_name }}.key'
        mode: '0400'
        force: no
      notify: reload nginx
    - name: x509 chain
      ansible.builtin.copy:
        src: '{{ site.x509_stapling_chain }}'
        dest: '{{ tls_certs_dir }}/{{ site.x509_stapling_chain | basename }}'
        mode: '0644'
      when: site.x509_stapling_chain != ""
      notify: reload nginx
  when: '"tls_cert" in site and site.tls_cert != ""'

- name: site config
  ansible.builtin.template:
    dest: '{{ nginx_etcdir }}/servers.d/{{ site.id }}.conf'
    src: '{{ lookup("first_found", siteconf_locations) }}'
  notify: reload nginx

- name: monitoring
  block:
    - name: create to_monitor entry
      ansible.builtin.set_fact:
        tmpmon:
          - proto: '{% if site.tls_cert or (proxified_by | count > 0) %}https{% else %}http{% endif %}'
            name: '{{ site.name }}'
            path: '{{ site.fcgi_status_path }}'
            type: fcgi-status
    - name: fcgi-status to_monitor
      ansible.builtin.set_fact:
        to_monitor: '{{ to_monitor | default([]) | union(tmpmon) }}'
        cacheable: yes
  when: '"fcgi_status_path" in site and site.fcgi_status_path != ""'

- name: nginx_sites_done fact
  ansible.builtin.set_fact:
    nginx_sites_done: true
