---
siteconf_locations:
  - '{{ playbook_dir }}/templates/{{ site.id }}/nginx/site.conf.j2'
  - '{{ playbook_dir }}/files/{{ site.id }}/nginx/site.conf'
  - '{{ playbook_dir }}/templates/{{ inventory_hostname |regex_replace("[0-9]$","") }}/nginx/{{ site.id }}.conf'
  - '{{ playbook_dir }}/files/{{ inventory_hostname |regex_replace("[0-9]$","") }}/nginx/{{ site.id }}.conf'
  - templates/site.conf.j2

include_locations:
  - '{{ playbook_dir }}/templates/{{ site.id }}/nginx'
  - '{{ playbook_dir }}/files/{{ site.id }}/nginx'
  - '{{ playbook_dir }}/files/{{ inventory_hostname |regex_replace("[0-9]$","") }}/nginx'
  - 'templates/nginx'
  - '{{ playbook_dir }}/files/nginx'
  - '{{ playbook_dir }}'

ips: '{% if "listen" in onesite %}{{ onesite.listen | map("regex_replace",":[0-9]*$","") | list }}{% else %}[]{% endif %}'

port: '{% if "listen" in onesite and onesite.listen | join(" ") is search(":[0-9]+") %}{{ onesite.listen | join(" ") | regex_replace("^.*:([0-9]+)$","\\1") }}{% else %}{% if site.tls | default(False) %}443{% else %}80{% endif %}{% endif %}'

# site par defaut
default_site:
  id: default
  name: ''
  aliases: []
  nginx_includes: []
  rootdir: '{{ onesite_home | default("/home/"+onesite.id) }}/{{ onesite.id }}'
  rootsrc: ''
  listen_ips: '{{ ips }}'
  tls: '{% if "tls_cert" in onesite %}True{% else %}False{% endif %}'
  tls_only: '{% if "tls_cert" in onesite %}True{% endif %}'
  http2: '{% if "http2" in onesite %}{{ onesite.http2 | bool }}{% else %}{{ do_http2 | bool }}{% endif %}'
  hsts: '{% if "tls_cert" in onesite and not ( "tls_only" in onesite and not onesite.tls_only ) %}31536000{% else %}0{% endif %}'
  tls_redirect: False
  tls_cert: ''
  tls_key: ''
  cert_name: '{% if onesite.name | default("") != "" %}{{ onesite.name | regex_replace("\*","wildcard") }}{% else %}{{ onesite.id }}{% endif %}'
  x509_stapling_chain: '{{ x509_stapling_chain | default("") }}'
  backends: []
  default_index: 'index.html index.htm index.txt'
  status_path: '{{ nginx_status_path }}'
  nginx_done: True
  proxified_by: '{{ proxified_by | default([]) }}'
  upstream: '{{ onesite.id }}'

#site: '{{ default_site | combine(onesite) }}'

