---
siteconf_locations:
  - '{{ playbook_dir }}/templates/{{ site.id }}/nginx/site.conf.j2'
  - '{{ playbook_dir }}/files/{{ site.id }}/nginx/site.conf'
  - '{{ playbook_dir }}/templates/{{ inventory_hostname |regex_replace("[0-9]$","") }}/nginx/{{ site.id }}.conf'
  - '{{ playbook_dir }}/files/{{ inventory_hostname |regex_replace("[0-9]$","") }}/nginx/{{ site.id }}.conf'
  - templates/site.conf.j2

include_locations:
  - '{{ playbook_dir }}/templates/{{ site.id }}/nginx'
  - '{{ playbook_dir }}/files/{{ site.id }}/nginx'
  - '{{ playbook_dir }}/files/{{ inventory_hostname |regex_replace("[0-9]$","") }}/nginx'
  - 'templates/nginx'
  - '{{ playbook_dir }}/files/nginx'

ips: '{% if "listen" in onesite %}{{ onesite.listen | map("regex_replace",":[0-9]*$","") | list }}{% else %}["*"{% if ansible_all_ipv6_addresses | count > 0 %},"[::]"{% endif %}]{% endif %}'

port: '{% if "listen" in onesite and onesite.listen | join(" ") is search(":[0-9]a$+") %}{{ onesite.listen | join(" ") | regex_replace("^.*:([0-9]+)$","\\1") }}{% else %}{% if site.tls | default(False) %}443{% else %}80{% endif %}{% endif %}'

# site par defaut
default_site:
  id: default
  name: ''
  aliases: []
  nginx_includes: []
  rootdir: '{{ onesite_home | default("/home/"+onesite.id) }}/{{ onesite.id }}'
  rootsrc: ''
  listen_ips: '{{ ips }}'
  tls: '{% if "tls_cert" in onesite %}True{% endif %}'
  http2: '{% if "http2" in onesite %}{{ onesite.http2 }}{% else %}{{ do_http2 }}{% endif %}'
  hsts: '{% if "tls_cert" in onesite %}31536000{% else %}0{% endif %}'
  tls_redirect: False
  tls_cert: ''
  tls_key: ''
  x509_stapling_chain: ''
  backends: []
  default_index: 'index.html index.htm index.txt'
  status_path: '{{ nginx_status_path }}'
  nginx_done: True

#site: '{{ default_site | combine(onesite) }}'

